#fundamental concepts of tensors using tensorflow 


In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)


2.4.1


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check number of dimentions
scalar.ndim

0

In [ ]:
# Create vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check dimention of the vector
vector.ndim

1

In [ ]:
# Create matrix
matrix = tf.constant([[10,8],[8,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [ 8, 10]], dtype=int32)>

In [ ]:
# Check dimention of matrix 
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# Check dimention of another matrix
another_matrix.ndim

2

In [ ]:
# Create a tensor
